### ISSUE TITLE
Visual Studio Project Failing to Build

### ISSUE THREAD

**Issue by jmw992** [arnaldog12/Tensorflow-Build-MT#1]
Want to say appreciate you for putting this up. I've followed the tutorial but haven't been able to get the final visual studio project to build.  When I build I get a C101 error below

Code	Description	Project	File	Line	Suppression State Error	
C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?	tensorflow_test_2	c:\users\jwcpp\source\repos\tensorflow_test_2\tensorflow_test_2\tensorflow_test_2.cpp	57	

I've tried going into visual studio project properties and changing the setting from Use to Not Using Precompiled Headers in the location below

Configuration Properties->C/C++->Precompiled Headers->Precompiled Header

But when building after changing it I am flooded with LINK2038 errors mismatch detected.  Any chance you may have some insight on how to handle this header issue?  I am building this on windows 10 with visual studio 2017, CUDA 9.0.176  CUDNN 7.21.38

**Comment by arnaldog12** [comment]
Hi, @jmw992 

First of all, thanks for your interest in this repo.

Are you trying to build the Tensorflow v1.4 for GPU? If you are, there is a [known issue](https://github.com/tensorflow/tensorflow/issues/14244) that __Tensorflow v1.4 doesn't support CUDA 9 and CUDNN version higher than 6__.

If you think there is a problem with project settings as well, you may take a look on the [vsproject](https://github.com/arnaldog12/Tensorflow-Build-MT/tree/master/v1.4) inside v1.4 folder. Open it on Visual Studio and check the project properties for the correspoding build type (CPU/GPU).

**Comment by jmw992** [comment]
Yeah I was following the instructions on your medium post directly, which didn't mention that potential conflict.  I am following the instructions within your v1.4 folder for gpu integration.  Will update you on how it goes, thanks for the fast response.

**Comment by arnaldog12** [comment]
Ok. The instructions in this repo are up to date. You better follow them, actually. I need to update instructions from Medium's post. I'll do that as soon as I can.

**Comment by jmw992** [comment]
I got it to work.  Thanks for the pointer and excellent instruction set on github.  I'm dropping in the text file I had used for linking all of the libraries.  Hopefully it will save people some typing in the future.

[VS_project_links_arnaldo_gpu.txt](https://github.com/arnaldog12/Tensorflow-Build-MT/files/2307958/VS_project_links_arnaldo_gpu.txt)

**Comment by arnaldog12** [comment]
Nice to hear that!
That's a good suggestion. Maybe I will replace the images by text in the future to make it easier.

I'm closing the issue then. Please, star the repo and leave some claps at the Medium post 😉
